// <auto-generated />
using System;
using MagicVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230817110523_SeedVillaTable")]
    partial class SeedVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "It is the villa for kings and queens",
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/fe/c7/a2/one-bedroom-pool-villa.jpg?w=1200&h=-1&s=1",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "It is the villa for Bronze Peuple",
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/fe/c7/a2/one-bedroom-pool-villa.jpg?w=1200&h=-1&s=1",
                            Name = "Bronze Villa",
                            Occupancy = 3,
                            Rate = 50.0,
                            Sqft = 200,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "It is the villa for Silver People",
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/fe/c7/a2/one-bedroom-pool-villa.jpg?w=1200&h=-1&s=1",
                            Name = "Silver Villa",
                            Occupancy = 4,
                            Rate = 70.0,
                            Sqft = 250,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "It is the villa for Gold People",
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/fe/c7/a2/one-bedroom-pool-villa.jpg?w=1200&h=-1&s=1",
                            Name = "Gold Villa",
                            Occupancy = 5,
                            Rate = 100.0,
                            Sqft = 350,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "It is the villa for Diamond People",
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/fe/c7/a2/one-bedroom-pool-villa.jpg?w=1200&h=-1&s=1",
                            Name = "Diamond Villa",
                            Occupancy = 6,
                            Rate = 250.0,
                            Sqft = 400,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
