// <auto-generated />
using System;
using CarAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarAPI.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EngineSize")
                        .HasColumnType("int");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasTurbo")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 8, 18, 17, 9, 15, 336, DateTimeKind.Local).AddTicks(8514),
                            EngineSize = 2000,
                            Fuel = "Deisel",
                            HasTurbo = true,
                            Manufacturer = "BMW",
                            Model = "M5",
                            Price = 25000.0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vin = 123
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 8, 18, 17, 9, 15, 336, DateTimeKind.Local).AddTicks(8524),
                            EngineSize = 3000,
                            Fuel = "Petrol",
                            HasTurbo = true,
                            Manufacturer = "Lamborghini",
                            Model = "Hurcan",
                            Price = 35000.0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vin = 931
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 8, 18, 17, 9, 15, 336, DateTimeKind.Local).AddTicks(8526),
                            EngineSize = -1,
                            Fuel = "electricity",
                            HasTurbo = false,
                            Manufacturer = "Tesla",
                            Model = "X",
                            Price = 10000.0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Vin = 323
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
